/*
 * Copyright (c) 2021 the original author or authors.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package science.aist.machinelearning.core;

import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.NodeEntity;

/**
 * Specific Implementation of the Gene Class representing a Genome in a machinelearning {@link Problem}
 *
 * @author Daniel Wilfing
 * @since 1.0
 */
@NodeEntity
public class ProblemGene<PT> extends Gene<PT> {

    /**
     * Id generated by database
     */
    @Id
    private Long id;

    /**
     * Human readable problem gene description.
     */
    private String description;

    public ProblemGene() {
    }

    public ProblemGene(PT gene) {
        this.gene = gene;
        this.description = this.toString();
    }

    @Override
    public String toString() {
        return "ProblemGene{" +
                "gene=" + (gene != null ? gene.toString() : "NULL") +
                '}';
    }

    public Long getId() {
        return id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
